# Generated by Django 6.0.6 on 2026-07-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
